### ISSUE TITLE
Redbird client as a stored class property

### ISSUE THREAD

**Issue by michalkalinowski-** [czechboy0/Redbird#25]
Hello,

More a question than an issue: i'm playing with your redis client and I'm wrapping it in a class to abstract db specific stuff in my app. I have a problem initializing this class though since init of Redis throws.

Here's what I'm trying to do:
```
class RedisManager {
  let client: Redbird
  init(address: String, port: UInt16, password: String? = nil) {
    do {
      let config = RedbirdConfig(address: address, port: port, password: password)
      client = try Redbird(config: config)
    } catch {
      Log.error("Could not connect to Redis instance")
    }
  }
...
# Api like setArray, getString ...
}
```
This fails with error:

> Return from initializer without initializing all stored properties

I want to keep an instance of Redis as a stored property because it seems wasteful to recreate it inside a do catch every time I want to access db.

Any idea how to instantiate Redis in init of my class and assign it to self.client?

**Comment by czechboy0** [comment]
Yeah I definitely recommend keeping just one connection open instead of creating it every time.

The problem is that when `Redbird` throws an error, you catch it, log, but don't assing into the `client` variable.

I'd recommend making the `RedisManager` throwing initializer, so change it to 

```
class RedisManager {
  let client: Redbird
  init(address: String, port: UInt16, password: String? = nil) throws {
      let config = RedbirdConfig(address: address, port: port, password: password)
      client = try Redbird(config: config)
  }

```

This way, if the creation of `RedisManager` throws, you know you can't access it. On the other hand, if it runs the initializer successfully, you know you're connected and everything should work fine.

With the changes above the compiler error should go away.
Please let me know if this helped 😊

**Comment by michalkalinowski-** [comment]
ok, thanks for the reply. I'm still getting used to the new way of handling errors in Swift :)

**Comment by czechboy0** [comment]
Happy to help :blush:
